Gavin Gunawardena \
INFS 770 \
Assignment 2 \
Dr. Liu

*Note: Some code, mainly the functions used in tasks 5 & 9 of this assignment are taken from the Jupyter notebook, 
ml_100k, provided by the professor. \
Setup: Data Imports

In [1]:
#Library Imports
import pandas as pd
import numpy as np
import re
# import the functions for cosine distance, euclidean distance, and the correlation distance
from scipy.spatial.distance import cosine, euclidean
from sklearn.model_selection import train_test_split

Task 1: Import data

In [2]:
# Task 1: Import data and print number of unique users and books in dataset
df_initial_data = pd.read_csv("DBbook_train_ratings.tsv", # the location to the data file
                       sep="\t", # for tab delimited documents, use "\t" as the seperator
                       skiprows = 1,
                       names=["userID", "itemID", "rating" ] # define the names for the four columns
                       )
#
#print(df_initial_data.head())
print("Unique users: %d" % len(df_initial_data["userID"].unique()))
print("Unique items: %d" % len(df_initial_data["itemID"].unique()))
df_initial_data.head()

Unique users: 6181
Unique items: 6166

   userID  itemID  rating
0    6873    3201       4
1    6873    3098       4
2    6873    4198       4
3    6873    5950       4
4    6873     204       4

Task 2: Create Utility matrix

In [3]:
# Task 2: Create utility matrix, filling empty cells with 0, and print the first 10 rows
#initial creation of matrix
matrix_data = pd.pivot_table(df_initial_data, values='rating', index=['userID'],columns=['itemID'])
#print top 10 rows
display(matrix_data.head(10))
#Print number and percentage of unpopulated cells
print("Number of unpopulated cells: %d" % len(matrix_data.isnull()))
cell_count = len(matrix_data.isnull()) + len(matrix_data.notnull())
print("Number of unpopulated cells:", len(matrix_data.isnull())/cell_count*100, end = "%")
#replace NA values with 0
matrix_data = matrix_data.fillna(0)

itemID,1,2,3,5,7,8,9,11,12,13,...,8157,8160,8161,8162,8163,8164,8166,8167,8168,8169
userID,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Number of unpopulated cells: 6181
Number of unpopulated cells: 50.0%

Task 3: Print the top 5 similar users to userID 2 based on Euclidean distance

In [4]:
#Task 3: Print top 5 users similar to userID 2 by Euclidean distance
# define a functions, which takes the given user number (integer) as the input 
#and returns the top K similar users (in a data frame)
def top_k_users(user_number, k):
    # no need to transpose the matrix this time because the rows already represent users
    # remove the active user
    df_sim = matrix_data[matrix_data.index != user_number].copy()
    # calculate the distance for between the given user and each row
    df_sim["distance"] = df_sim.apply(lambda x: euclidean(matrix_data.loc[user_number,], x), axis=1)
    # return the top k from the sorted distances
    return df_sim.sort_values(by="distance").head(k)["distance"] 

#Use the function
top_k_users(2, 5)

userID
3917    11.401754
6875    12.569805
986     12.806248
1983    12.884099
1156    12.922848
Name: distance, dtype: float64

Task 4: Print the Euclidean distance between items 18 and 1, & 36 and 1. Next write a print statement that tells between 36 and 18, which item is more similar to 1 and why.

In [5]:
#Task 4: Print the Euclidean distance between items 18 and 1, & 36 and 1. 
#Next write a print statement that tells between 36 and 18, which item is more similar to 1 and why.
#Define a function to find distance between 2 items
def find_euc_dist(item1, item2):
    return euclidean(matrix_data[item1],matrix_data[item2])
#Print distance between items 18 and 1
print("Distance between items 18 and 1: ", find_euc_dist(18,1))
#Print distance between items 36 and 1
print("Distance between items 36 and 1: ", find_euc_dist(36,1))
#Print which item is more similar to 1 and why
print("Item 18 is more similar to 1 because on a dimensional grid and measuring via the Pythagoras theorem, the data points generated by the ratings for 18 and 1 are closer compared to the data points generated by the ratings of 36 and 1.")

Distance between items 18 and 1:  29.189039038652847
Distance between items 36 and 1:  40.124805295477756
Item 18 is more similar to 1 because on a dimensional grid and measuring via the Pythagoras theorem, the data points generated by the ratings for 18 and 1 are closer compared to the data points generated by the ratings of 36 and 1.

Task 5: Print the top 5 similar items to itemID 8010.

In [6]:
#Task 5: Print the top 5 similar items to itemID 8010.
# define a functions, which takes the given item number (integer) as the input 
#and returns the top K similar items (in a data frame)
def top_k_items(item_number, k):
    # copy the dense matrix and transpose it so each row represents an item
    df_sim = matrix_data.transpose()
    # remove the active item 
    df_sim = df_sim.loc[df_sim.index != item_number]
    # calculate the distance between the given item for each row (apply the function to each row if axis = 1)
    df_sim["distance"] = df_sim.apply(lambda x: euclidean(matrix_data[item_number], x), axis=1)
    # return the top k from the sorted distances
    return df_sim.sort_values(by="distance").head(k)["distance"]   
# retrieve top five similar items to Item 8010
top_k_items(8010, 5)

itemID
3711    127.921851
4559    127.964839
330     129.715072
1311    129.722781
7328    129.761319
Name: distance, dtype: float64

Task 6: Remove books and users with less than 20 rating scores from the utility matrix.

In [7]:
#Task 6: Remove books and users with less than 20 rating scores from the utility matrix.
#View shape of matrix before adjustment
print("Shape of the user-item matrix before adjustment: %d x %d" % matrix_data.shape)
#Make the adjustment of removing books and users with less than 20 rating scores
df_item_fre = df_initial_data.groupby("itemID").count()
df_user_fre = df_initial_data.groupby("userID").count()
matrix_data_adj6 = matrix_data.copy()
selected_items = df_item_fre[df_item_fre["userID"]>20].index
matrix_data_adj6 = matrix_data_adj6[selected_items]
selected_users = df_user_fre[df_user_fre["itemID"]>20].index
matrix_data_adj6 = matrix_data_adj6.loc[selected_users]
#View shape of matrix after adjustment
print("Shape of the user-item matrix after adjustment: %d x %d" % matrix_data_adj6.shape)

Shape of the user-item matrix before adjustment: 6181 x 6166
Shape of the user-item matrix after adjustment: 766 x 776

Task 7: Use the task 6 dataset and remove users that haven't rated itemID 8010. Next print counts of the different rating sccores of this item and the shape of the dataset.

In [8]:
#Task 7: Use the task 6 dataset and remove users that haven't rated itemID 8010. 
#Next print counts of the different rating sccores of this item and the shape of the dataset.
#Remove users that haven't rated itemID 8010
user_query_7 = matrix_data_adj6[matrix_data_adj6[8010]!=0].index
matrix_data_adj7 = matrix_data_adj6.loc[user_query_7]
#Print counts of the different rating scores of itemID 8010
print(matrix_data_adj7[8010].value_counts())
#Print shape of the dataset after itemID 8010 removal
print("Shape of the user-item matrix after adjustment: %d x %d" % matrix_data_adj7.shape)

4.0    68
5.0    58
3.0    27
2.0    13
1.0     8
Name: 8010, dtype: int64
Shape of the user-item matrix after adjustment: 174 x 776

Task 8: Partition the data set obtained from step 7. Randomly select 25% of users as the testing set, and the others as the training set.  Next, print dimensions of the training and testings sets and print the mean rating of itemID 8010 in the training and testing sets

In [9]:
#Task 8: Partition the data set obtained from step 7. 
#Randomly select 25% of users as the testing set, and the others as the training set.  
#Next print dimensions of the training and testings sets and print the mean rating of 
#itemID 8010 in the training and testing sets
#Partition into training and test datasets


# create a data frame for the predictors
df_x = matrix_data_adj7[[col for col in matrix_data_adj7.columns if col != 8010]]


# create a series for the outcome
df_y = matrix_data_adj7[[8010]]

#Split the dataset 75% for training and 25% for testing; and set the response and independent variables
train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.25, random_state=0)
df_train_x = pd.DataFrame(train_x, columns=df_x.columns)
df_test_x = pd.DataFrame(test_x, columns=df_x.columns)
df_train_y = pd.DataFrame(train_y, columns=[8010])
df_test_y = pd.DataFrame(test_y, columns=[8010])

#Print dimensions of the datasets
print("Shape of training dataset: %d x %d" % df_train_x.merge(df_train_y, how="inner", on="userID").shape)
print("Shape of test dataset: %d x %d" % df_test_x.merge(df_test_y, how="inner", on="userID").shape)
#Print the mean rating of itemID 8010 in the training and test datasets
print("Mean rating of itemID 8010 in training dataset: %d" % df_train_y.mean()) 
print("Mean rating of itemID 8010 in test dataset: %d" % df_test_y.mean())

Shape of training dataset: 130 x 776
Shape of test dataset: 44 x 776
Mean rating of itemID 8010 in training dataset: 3
Mean rating of itemID 8010 in test dataset: 3

Task 9: Use the training and test datasets obtained in task 8 and print the userID of the user in the 5th row of the test dataset. Predict their rating of  itemID 8010 based on the top 5 similar users in the training dataset. Next print their predicted raing and actual rating.

In [10]:
#Task 9: Use the training and test datasets obtained in task 8 and print the userID of the 
#user in the 5th row of the test dataset. Predict their rating of itemID 8010 based 
#on the top 5 similar users in the training dataset. Next print their predicted raing and actual rating.
#Print the userID of  the user in the 5th row in the test dataset
print("userID value of the 5th row in the test dataset: %d" % df_test_x.index[4])
#Predict this user's rating of itemID 8010 based on top 5 similar users in the training dataset
# specify the number of similar users to retrieve
k = 5
#Function for making prediction based on users with the closest euclidean distance to the selected user
def user_based_predict(user_number):
    # retrieve the top k similar users
    # copy from all the training predictors
    df_sim = df_train_x.copy()
    # for each user, calculate the distance between this user and the active user
    df_sim["distance"] = df_sim.apply(lambda x: euclidean(df_test_x.loc[user_number], x), axis=1)
    # create a new data frame to store the top k similar users
    df_sim_users = df_sim.loc[df_sim.sort_values(by="distance").head(k).index]
    # calculate these similar users' rating on 151, weighted by distance
    df_sim_users["weighed_d"] = list(map(lambda x: df_sim_users.loc[x]["distance"]*df_train_y.loc[x][8010], df_sim_users.index))
    predicted = df_sim_users["weighed_d"].sum()/df_sim_users["distance"].sum()
    return predicted
#Print the user's predicted rating and actual rating
uid = 5614
print("Predicted rating on Item 8010:", user_based_predict(uid))
print("True rating on Item 8010:     ", df_test_y.loc[uid][8010])

userID value of the 5th row in the test dataset: 5614
Predicted rating on Item 8010: 4.013489148846391
True rating on Item 8010:      4.0

1)	Use your own language (<= 6 sentences) to briefly describe content-based filtering.  \
*Content-based filtering involves building separate profiles for lists of items and users that are made up of vectors of scores(that represent preferences of the user or related descriptions of items). Once the profiles are built, you can find the dot products of the vectors that make up the profiles in order to measure similarity, with a larger dot product representing profiles that are more similar. This is used in recommender systems by using the profiles of users that have features scored based on user activity and the profiles of items that have the same features as the user profiles but that are scored based on descriptions of items. These scores  make up vectors and the dot product of these vectors are obtained to find what would be best to recommend to specific users. Also, missing features for user profiles are derived via statistical models such as linear regression while the items usually never have missing features and thus content-filtering can suffer from low accuracy until the missing features for users are filled in.* \
2)	There are different models that can used in model-based collaborative filter such as SVD and neural network. In  \this course, I just introduced SVD model based collaborative filtering, which is the most commonly used collaborative  \filtering algorithm. Use your own language (<= 6 sentences) to briefly describe SVD model-based collaborative filtering () \
*Similarly to content-based filtering, Singular Value Decomposition model-based collaborative filtering is used for recommender systems. The idea of model-based collaborative filtering is that you start off with a sparse matrix, which is a matrix with missing values, that relates users with items and contains gathered ratings on what items specific users like. Matrix decomposition is used to split the matrix into 3 smaller matrices, and then matrix  recomposition is  used to combine these 3  matrices into 1 matrix. This final matrix will not have missing values and all previously missing values will be replaced with predicted values  through the matrix recomposit00ion process.*\
3)	Summarize the differences between content-based filtering and SVD model-based collaborative filtering? (at least  \two differences).  \
*Differences include how content based filtering prioritizes content features while SVD model-based collaborative filtering prioritizes user preference. Content based filtering provides more accurate recommendations due to its focuson content a user likes, while SVD model-based collaborative filtering can be inaccurate due to relying on the assumption that users with similar preferences always like the same products. Finally, content-based filtering requires a fileld in content profile and user profile while SVD model-based collaborative filtering requires a filled in user profile to suggest relevant content.*